[workspace]
authors = [
    "Brett Nelson <brettleenelson@gmail.com>",
    "Paul Varkey <paul.varkey@gmail.com>",
    "Eeron Grant <eerongrant@gmail.com>",
]
channels = ["conda-forge"]
name = "pace"
platforms = ["osx-arm64", "osx-64", "linux-64"]
version = "0.1.0"

[tasks]


# dev tools
[feature.dev-tools.dependencies]
black = ">=26.5.1,<27"
ruff = ">=0.16.4,<0.17"
mypy = ">=2.3.1,<3"
pytest = ">=9.1.1,<10"
pre-commit = ">=4.6.2,<5"

# conda-forge installs
[feature.pace-py.dependencies]
python = ">=3.11,<3.12"
fastapi = "*"

# pypi-specific installs
[feature.pace-py.pypi-dependencies]
pace = { path = "src-py", editable = true }

# no apple-silicon implementation of openmc so we limit any
# builds which include openmc to osx-64 (would require
# emulation on apple silicon), or linux...
[feature.openmc]
platforms = ["osx-64", "linux-64"]

[feature.openmc.dependencies]
openmc = "*"

# cpp-specific stuff
[feature.cpp-build.dependencies]
cmake = "*"
compilers = "*"

# rust-specific stuff
[feature.rust-build.dependencies]
rust = "*"

[environments]
no-phys-dev = [
    "dev-tools",
    "pace-py",
] # service/API work, src-py only, no OpenMC —- native osx-arm64, or osx-64/linux-64
py-phys-dev = [
    "dev-tools",
    "pace-py",
    "openmc",
] # OpenMC-dependent work, src-py only —- osx-64/linux-64 only
full-phys-dev = [
    "dev-tools",
    "pace-py",
    "openmc",
    "cpp-build",
    "rust-build",
] # OpenMC-dependent work with cpp/rs —- osx-64/linux-64 only
